import { StyleSheet, BackHandler } from 'react-native'
import { scaleSize, scaleFont } from '@utils/scaleUtil'

export default StyleSheet.create({
    pages:{
        backgroundColor:'#fff',
        paddingBottom:scaleSize(200)
    },
    qrItemBox:{
        borderTopWidth:scaleSize(2),
        borderColor:'#f2f2f2',
        height:scaleSize(150),
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        paddingLeft:scaleSize(54),
        paddingRight:scaleSize(54)
    },
    qrItem:{
        display:'flex',
        flexDirection:'row'
    },
    scanIcon:{
        width:scaleSize(50),
        height:scaleSize(50),
        marginRight:scaleSize(34),
        backgroundColor:'red',
        marginTop:scaleSize(48)
    },
    scanText:{
        fontSize:scaleFont(48),
        color:'#333',
        lineHeight:scaleSize(150)
    },
    arrowText:{
        fontSize:scaleFont(36),
        color:'#999',
        lineHeight:scaleSize(150)
    },
    arrowIcon:{
        width:scaleSize(30),
        height:scaleSize(30),
        backgroundColor:'red',
        marginTop:scaleSize(60),
        marginLeft:scaleSize(6)
    },
    qrCodeWrapper:{
        borderTopWidth:scaleSize(24),
        borderColor:'#f2f2f2',
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    qrBg:{
        width:scaleSize(800),
        height:scaleSize(1000),
        marginTop:scaleSize(220),
        position:'relative',
        display:'flex',
        flexDirection:'column',
        justifyContent:'center'
    },
    avatar:{
        position:'absolute',
        top:scaleSize(-100),
        width:scaleSize(240),
        height:scaleSize(240),
        borderRadius:scaleSize(120)
    },
    userName:{
        fontSize:scaleFont(48),
        color:'#564f5f',
        textAlign:'center',
        marginTop:scaleSize(32)
    },
    qrCode:{
        width:scaleSize(520),
        height:scaleSize(520),
        backgroundColor:'red',
        marginTop:scaleSize(62)
    },
    operationBox:{
        marginTop:scaleSize(100),
        paddingLeft:scaleSize(327),
        paddingRight:scaleSize(327),
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between'
    },
    operationItem:{
        display:'flex',
        flexDirection:'column'
    },
    btnIcon:{
        width:scaleSize(66),
        height:scaleSize(66),
        marginBottom:scaleSize(12)
    },
    btnText:{
        fontSize:scaleFont(32),
        color:'#333'
    },
    slogan:{
        marginTop:scaleSize(66),
        textAlign:'center',
        color:'#333',
        fontSize:scaleFont(52)
    }
})