import { StyleSheet } from 'react-native'
import { scaleSize, scaleFont } from '@utils/scaleUtil'

export default StyleSheet.create({
    editInfoWrap:{
        backgroundColor:'#fff'
    },
    editInfoMain:{
        backgroundColor:'#564F61',
        height:scaleSize(550),
    },
    avatarWrap:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        marginTop:scaleSize(80),
        marginBottom:scaleSize(22)
    },
    avatarItemWrap:{
        position:'relative',
        width:scaleSize(266),
        height:scaleSize(266)
    },
    avatarItem:{
        width:scaleSize(266),
        height:scaleSize(266),
        borderRadius:scaleSize(133)
    },
    avatarCamera:{
        width:scaleSize(74),
        height:scaleSize(74),
        position:'absolute',
        right:0,
        bottom:0
    },
    avatarEdit:{
        fontSize:scaleFont(40),
        color:'#fff',
        textAlign:'center',
        marginBottom:scaleSize(22)
    },
    avatarCoverWrap:{
        position:'relative',
        overflow:'hidden',
        height:scaleSize(74)
    },
    avatarCoverBtn:{
        borderRadius: scaleSize(37),
        width:scaleSize(220),
        height:scaleSize(74),
        position:'absolute',
        right:scaleSize(52),
        backgroundColor:'#fff'
    },
    avatarCover:{
        color:'#333',
        fontSize:scaleFont(40),
        lineHeight:scaleSize(74),
        textAlign:'center'
    },
    infoFormWrap:{
        paddingLeft:scaleSize(54),
        paddingRight:scaleSize(54)
    },
    infoFormItem:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        height:scaleSize(160),
        borderBottomWidth:1,
        borderColor:'#f2f2f2',
        borderStyle:'solid'
    },
    formItemTitle:{
        fontSize:scaleFont(42),
        color:'#564F5F',
    },
    arrow:{
        width:scaleSize(60),
        height:scaleSize(60)
    },
    chatWrap:{
        height:scaleSize(354),
        paddingLeft:scaleSize(54),
        paddingRight:scaleSize(54),
        display:'flex',
        alignItems:'center',
        flexDirection:'row'
    },
    tbears:{
        width:scaleSize(60),
        height:scaleSize(60),
        marginRight:scaleSize(24)
    },
    tbearsChat:{
        width:scaleSize(900),
        height:scaleSize(200),
        backgroundColor:'#f1f0fa',
        borderRadius:scaleSize(10),
        padding:scaleSize(40)
    },
    tbearsChatText:{
        fontSize:scaleFont(42),
        color:'#564F5F',
        lineHeight:scaleSize(50)
    },
    hobbyWrap:{
        paddingLeft:scaleSize(54),
        paddingRight:scaleSize(54),
        height:scaleSize(960),
        display:'flex',
        flexDirection:'column'
    },
    hobbyList:{
        position:'relative'  
    },
    hobbyItem:{
        fontSize:scaleSize(42),
        color:'#564F5F'
    },
    hobbyAddBtn:{
        marginTop:scaleSize(100),
        marginBottom:scaleSize(92),
        textAlign:'center',
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    hobbyAddBtnText:{
        fontSize:scaleFont(42),
        color:'#999'
    }
})