import { StyleSheet } from 'react-native'
import { scaleSize, scaleFont } from '@utils/scaleUtil'

export default StyleSheet.create({
    storeWrap:{
        
    },
    storeCountWrap:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        marginBottom:scaleSize(25),
        marginTop:scaleSize(54)
    },
    storeCountBox:{
        width:scaleSize(970),
        borderRadius:scaleSize(20),
        backgroundColor:"#fff",
        paddingTop:scaleSize(54)
    },
    storeCountNum:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        borderBottomWidth:1,
        borderStyle:'solid',
        paddingBottom:scaleSize(60),
        borderColor:'#f2f2f2'
    },
    storeCountItem:{
        flex:1,
    },
    storeNumber:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        marginBottom:scaleSize(39),
    },
    storeMoney:{
        fontSize:scaleFont(60),
        color:'#333'
    },
    storeYuan:{
        fontSize:scaleFont(48),
        color:'#333',
        lineHeight:scaleFont(75)
    },
    storeNumberTitle:{
        textAlign:'center',
        fontSize:scaleFont(42),
        color:'#333',
    },
    storeCount:{
        height:scaleSize(453),
        width:scaleSize(972),
        borderRadius: scaleSize(26),
        borderWidth:1,
        borderColor:'#ccc',
    },
    storeTipsWrap:{
        padding:scaleSize(50)
    },
    storeTipsTitle:{
        color: '#333',
        fontSize:scaleFont(42),
        marginBottom:scaleSize(13)
    },
    storeTipsDes:{
        color: '#666',
        fontSize:scaleFont(39),
        lineHeight:scaleSize(54),
        marginBottom:scaleSize(22)
    },
    storeTipsPoint:{
        color: '#666',
        fontSize:scaleFont(39),
        lineHeight:scaleSize(54)
    },
    storeCountBtnBox:{
        display:'flex',
        flexDirection:'row',
        height:scaleSize(140),
        alignItems:'center'
    },
    storeCountBtnItem:{
        flex:1,
        textAlign:'center',
        color: '#7063E3',
        fontSize:scaleFont(42)
    },
    storeList:{
        height:scaleSize(330),
        marginLeft:scaleSize(60),
        marginRight:scaleSize(60),
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-around',
        backgroundColor:'#fff',
        alignItems:'center',
        borderRadius:scaleSize(20)
    },
    storeIconBg:{
        width:scaleSize(150),
        height:scaleSize(150),
        backgroundColor:'#f1f1f1',
        borderRadius:scaleSize(75),
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    storeIcon:{
        width:scaleSize(90),
        height:scaleSize(90)
    },
    storeText:{
        textAlign:'center',
        fontSize: scaleFont(42),
        color:'#333',
        marginTop:scaleSize(12)
    }
})